// Code Generated by Sidekick is for learning and experimentation purposes only.
import express from 'express';
import { getInventorySummary } from  '../controllers/inventory.controller'
import { verifyToken } from '../middlewares/verifyToken';

const router = express.Router();

router.get('/inventory/summary', verifyToken, getInventorySummary);

export default router;
