// Code Generated by Sidekick is for learning and experimentation purposes only.
import express from 'express';
import { createStock } from '../controllers/stock.controller'
import { verifyToken } from '../middlewares/verifyToken'
import { verifyRole } from '../middlewares/verifyRole';

const router = express.Router();

router.post('/add-stock', verifyToken,verifyRole("manager") ,createStock);

export default router;
