// Code Generated by Sidekick is for learning and experimentation purposes only.
import express from 'express';
import { createTask } from "../controllers/task.controller"
import { verifyToken } from '../middlewares/verifyToken'
import { verifyRole } from '../middlewares/verifyRole';

const router = express.Router();

router.post('/create', verifyToken, verifyRole('manager'),createTask);

export default router;
