// Code Generated by Sidekick is for learning and experimentation purposes only.
import {Response, NextFunction } from 'express';
import { AuthenticatedRequest } from '../interfaces/authenticateRequest.interface';

export const verifyRole = (requiredRole: string) => {
    return (req: AuthenticatedRequest, res: Response, next: NextFunction): void => {
        
        if (req.role !== requiredRole) {
            res.status(403).json({ message: "Forbidden: You do not have the required role" });
            return;
        }
        next();
    };
};
