// Code Generated by Sidekick is for learning and experimentation purposes only.
import { Request, Response } from 'express';
import Stock from '../models/stock.model'

export const createStock = async (req: Request, res: Response): Promise<void> => {
    const { consumerName, productName, supplier, productId, quantity, price, sellingPrice,cashier,status} = req.body;
    

    try {
        const newStock = new Stock({
            consumerName,
            productName,
            supplier,
            productId,
            quantity,
            price,
            sellingPrice,
            cashier,
            status,
            dateAdded:new Date(),
        });

        const savedStock = await newStock.save();
        res.status(201).json(savedStock);
    } catch (error) {
        res.status(500).json({ message: 'Error creating stock', error });
    }
};
