// Code Generated by Sidekick is for learning and experimentation purposes only.
import mongoose, { Schema, Model } from 'mongoose';
import { IStock } from '../interfaces/stock.interface'

const stockSchema: Schema<IStock> = new Schema(
    {
        
        productId: { type: String, required: true,unique:true },
        productName: { type: String, required: true },
        supplier: { type: String, required: true },
        consumerName: { type: String, required: true },
        cashier: { type: String, required: true },
        quantity: { type: Number, required: true },
        price: { type: Number, required: true },
        sellingPrice: { type: Number, required: true },
        dateAdded: { type: Date, required: true },
        status: {
            type: String,
            required: true,
            enum: ['failed', 'completed',"closed","pending"],
            default: 'staff'
        },

    },
    { timestamps: true }
);

const Stock: Model<IStock> = mongoose.model<IStock>('Stock', stockSchema);

export default Stock;
